export default function(){
  return[
    {
      Key: 0,
      Name: 'Stephen Curry',
      Position: 'Guard',
      Team: 'GSW',
      Points: 0.75,
      Threes: 1,
      Rebounds: 0.37,
      Assists: 0.57,
      Steals: 0.75,
      Blocks: 0.05,
      Color: '#006BB6',
      rgbOpaque: 'rgba(0, 107, 182, 0.25)',
      Class: 'gsw-1'
    },
    {
      Name: 'DeMarcus Cousins',
      Position: 'Forward',
      Team: 'NOP',
      Points: 0.82,
      Threes: 0.51,
      Rebounds: 0.87,
      Assists: 0.28,
      Steals: 0.7,
      Blocks: 0.45,
      Color: '#724C9F',
      rgbOpaque: 'rgba(114, 76, 159, 0.25)',
      Class: 'sac-1'
    },
    {
      Key: 2,
      Name: 'Kevin Durant',
      Position: 'Forward',
      Team: 'GSW',
      Points: 0.8,
      Threes: 0.49,
      Rebounds: 0.6,
      Assists: 0.45,
      Steals: 0.35,
      Blocks: 0.6,
      Color: '#F05133',
      rgbOpaque: 'rgba(240, 81, 51, 0.25)',
      Class: 'okc-1'
    },
    {
      Key: 3,
      Name: 'Anthony Davis',
      Position: 'Forward',
      Team: 'NOP',
      Points: 0.84,
      Threes: 0.11,
      Rebounds: 0.87,
      Assists: 0.16,
      Steals: 0.50,
      Blocks: 0.87,
      Color: '#002b5c',
      rgbOpaque: 'rgba(0, 43, 92, 0.25)',
      Class: 'nop-1'
    },
    {
      Key: 4,
      Name: 'Draymond Green',
      Position: 'Forward',
      Team: 'GSW',
      Points: 0.3,
      Threes: 0.26,
      Rebounds: 0.66,
      Assists: 0.7,
      Steals: 0.8,
      Blocks: 0.6,
      Color: '#FDB927',
      rgbOpaque: 'rgba(253, 185, 39, 0.25)',
      Class: 'gsw-2'
    },
    {
      Key: 5,
      Name: 'James Harden',
      Position: 'Guard',
      Team: 'HOU',
      Points: 0.94,
      Threes: 0.92,
      Rebounds: 0.7,
      Assists: 1,
      Steals: 0.65,
      Blocks: 0.15,
      Color: '#ED174C',
      rgbOpaque: 'rgba(237, 23, 76, 0.25)',
      Class: 'det-1'
    },
    {
      Key: 6,
      Name: 'Russell Westbrook',
      Position: 'Guard',
      Team: 'OKC',
      Points: 1,
      Threes: 0.6,
      Rebounds: 0.8,
      Assists: 1,
      Steals: 0.8,
      Blocks: 0.4,
      Color: '#8E9090',
      rgbOpaque: 'rgba(142, 144, 144, 0.25)',
      Class: 'sac-2'
    },
  ]
}
